stages:
  preprocess:
    cmd: uv run python -m src.data.run_preprocess
    deps:
      - src/data
      - src/data/services
      - config/params.yaml
      - config/paths.yaml
    outs:
      - data/preprocessed

  train:
    cmd: >
      bash -c '
      if [ "$ENABLE_MLFLOW" = "1" ]; then
        python scripts/mlflow_train_wrapper.py
      else
        uv run python -m src.train_model.run_train --model_name bert-rakuten-final
      fi
      '
    deps:
      - src/train_model
      - src/train_model/services
      - data/preprocessed
      - config/params.yaml
      - config/paths.yaml
    outs:
      - models/bert-rakuten-final
    params:
      - training

  evaluate:
    cmd: >
      bash -c '
      if [ "$ENABLE_MLFLOW" = "1" ]; then
        python scripts/mlflow_evaluate_wrapper.py
      else
        uv run python -m src.evaluate_model.run_evaluate --model_name bert-rakuten-final
      fi
      '
    deps:
      - src/evaluate_model
      - src/evaluate_model/services
      - data/preprocessed
      - models/bert-rakuten-final
      - config/params.yaml
      - config/paths.yaml
    metrics:
      - metrics/metrics.json:
          cache: false
